import type { ShortcutEntry } from "./types";

export const GLOBAL_SHORTCUTS: ShortcutEntry[] = [
  {
    id: "quit_app",
    command: "Hold to quit application",
    macKeys: "⌘Q",
    winKeys: "Ctrl+Q",
    accelerator: "Ctrl+Q",
    scope: "global",
    category: "window",
  },
  {
    id: "close_tab",
    command: "Close current tab",
    macKeys: "⌘W",
    winKeys: "Ctrl+W",
    scope: "global",
    category: "window",
  },
  {
    id: "hide_window",
    command: "Minimize window",
    macKeys: "⌘M",
    winKeys: "Ctrl+M",
    scope: "global",
    category: "window",
  },
  {
    id: "maximize_work_station",
    command: "Maximize Workstation",
    macKeys: "⇧⌘M",
    winKeys: "Ctrl+Shift+M",
    accelerator: "Ctrl+Shift+M",
    scope: "global",
    category: "window",
  },
  {
    id: "open_my_station",
    command: "Open My Station",
    macKeys: "⌘1",
    winKeys: "Ctrl+1",
    scope: "global",
    category: "navigation",
  },
  {
    id: "open_agent_station",
    command: "Open Agent's Station",
    macKeys: "⌘2",
    winKeys: "Ctrl+2",
    scope: "global",
    category: "navigation",
  },
  {
    id: "open_kanban",
    command: "Open Kanban",
    macKeys: "⌘3",
    winKeys: "Ctrl+3",
    scope: "global",
    category: "navigation",
  },
  {
    id: "toggle_ade_manager",
    command: "Open ADE Manager",
    macKeys: "⌥⌘G",
    winKeys: "Ctrl+Alt+G",
    scope: "global",
    category: "view",
  },
  {
    id: "new_session",
    command: "Create new session",
    macKeys: "⌘N",
    winKeys: "Ctrl+N",
    accelerator: "Ctrl+N",
    scope: "global",
    category: "navigation",
  },
  {
    id: "new_tab",
    command: "New tab",
    macKeys: "⌘T",
    winKeys: "Ctrl+T",
    scope: "global",
    category: "navigation",
  },
  {
    id: "new_tab_alt",
    command: "New tab (alternative)",
    macKeys: "⌘L",
    winKeys: "Ctrl+L",
    scope: "global",
    category: "navigation",
  },
  {
    id: "open_settings",
    command: "Open settings",
    macKeys: "⌘,",
    winKeys: "Ctrl+,",
    accelerator: "Ctrl+,",
    scope: "global",
    category: "navigation",
  },
  {
    id: "toggle_spotlight",
    command: "Toggle spotlight",
    macKeys: "⇧⌘P",
    winKeys: "Ctrl+Shift+P",
    scope: "global",
    category: "navigation",
  },
  {
    id: "open_model_selector",
    command: "Open model selector",
    macKeys: "⌘/",
    winKeys: "Ctrl+/",
    accelerator: "Ctrl+/",
    scope: "global",
    category: "navigation",
  },
  {
    id: "open_workspace_selector",
    command: "Open working directory selector",
    macKeys: "⌘.",
    winKeys: "Ctrl+.",
    accelerator: "Ctrl+.",
    scope: "global",
    category: "navigation",
  },
  {
    id: "open_branch_selector",
    command: "Open branch selector",
    macKeys: "⌥⌘.",
    winKeys: "Ctrl+Alt+.",
    accelerator: "Ctrl+Alt+.",
    scope: "global",
    category: "navigation",
  },
  {
    id: "open_location_selector",
    command: "Open running-location selector",
    macKeys: "⇧⌘.",
    winKeys: "Ctrl+Shift+.",
    accelerator: "Ctrl+Shift+.",
    scope: "global",
    category: "navigation",
  },
  {
    id: "window_open_folder",
    command: "Open folder",
    macKeys: "⌘O",
    winKeys: "Ctrl+O",
    accelerator: "Ctrl+O",
    scope: "global",
    category: "file",
  },
  {
    id: "window_close",
    command: "Close window",
    macKeys: "⇧⌘W",
    winKeys: "Ctrl+Shift+W",
    accelerator: "Ctrl+Shift+W",
    scope: "global",
    category: "window",
  },
  {
    id: "next_tab",
    command: "Next tab",
    macKeys: "Ctrl+Tab / ⌘⌥→",
    winKeys: "Ctrl+Tab",
    scope: "global",
    category: "navigation",
  },
  {
    id: "previous_tab",
    command: "Previous tab",
    macKeys: "Ctrl+Shift+Tab / ⌘⌥←",
    winKeys: "Ctrl+Shift+Tab",
    scope: "global",
    category: "navigation",
  },
  {
    id: "zoom_in",
    command: "Zoom in",
    macKeys: "⌘++",
    winKeys: "Ctrl++",
    scope: "global",
    category: "view",
  },
  {
    id: "zoom_out",
    command: "Zoom out",
    macKeys: "⌘-",
    winKeys: "Ctrl+-",
    scope: "global",
    category: "view",
  },
  {
    id: "zoom_reset",
    command: "Reset zoom",
    macKeys: "⌘0",
    winKeys: "Ctrl+0",
    scope: "global",
    category: "view",
  },
  {
    id: "toggle_api_panel",
    command: "Toggle API panel",
    macKeys: "⌘5",
    winKeys: "Ctrl+5",
    scope: "global",
    category: "panels",
  },
  {
    id: "toggle_captions",
    command: "Toggle captions",
    macKeys: "⌥⌘C",
    winKeys: "Ctrl+Alt+C",
    scope: "global",
    category: "view",
  },
  {
    id: "toggle_inspect_mode",
    command: "Toggle inspect mode",
    macKeys: "⌘8",
    winKeys: "Ctrl+8",
    scope: "global",
    category: "debugging",
  },
  {
    id: "capture_component",
    command: "Capture component issue",
    macKeys: "⌘9",
    winKeys: "Ctrl+9",
    scope: "global",
    category: "debugging",
  },
];
