import { ACTION_ID } from "@src/ActionSystem/actionIds";

export const HOUSEKEEPER_DEFAULT_MODEL = "openbmb/MiniCPM5-1B";
export const HOUSEKEEPER_DEFAULT_BASE_URL = "http://127.0.0.1:8000/v1";
export const HOUSEKEEPER_SAFE_CONTEXT_TOKENS = 10000;
export const HOUSEKEEPER_CONFIDENCE_THRESHOLD = 0.7;

export const HOUSEKEEPER_ALLOWED_ACTION_IDS = [
  ACTION_ID.THEME_SET_SYSTEM,
  ACTION_ID.THEME_SET_LIGHT,
  ACTION_ID.THEME_SET_DARK,
  ACTION_ID.APP_GO_TO_MODEL_KEYS,
  ACTION_ID.APP_GO_TO_INTEGRATIONS,
  ACTION_ID.APP_GO_TO_HOUSEKEEPER,
  ACTION_ID.APP_OPEN_ADD_MODEL_API,
  ACTION_ID.SPOTLIGHT_OPEN,
  ACTION_ID.SPOTLIGHT_OPEN_AGENT_CONTROL,
  ACTION_ID.SPOTLIGHT_OPEN_SESSION_CREATOR,
] as const;
