//! Agent Org task-board tool entries.

use super::aliases::*;

pub(super) static TOOLS: &[ToolEntry] = &[
    ToolEntry {
        name: tool_names::TASK_CREATE,
        description: "Create a task on the Agent Org task board.",
        description_detail: "Creates a pending shared Task for the current Agent Org run, including its graph fields, execution mode, and optional worker Owner.",
        category: tool_categories::ORCHESTRATION,
        icon_id: "clipboard-copy",
        simulator_app: AppChannels,
        app_subtool: SubTodo,
        chat_block: CbOrgTask,
        hidden: true,
        label_running: "tools.taskCreateRunning",
        label_done: "tools.taskCreateDone",
        label_failed: "tools.taskCreateFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::TASK_GRAPH_CREATE,
        description: "Create an atomic Agent Org task graph.",
        description_detail: "Validates and creates a complete dependency graph in one transaction, using local node keys that resolve to durable task ids.",
        category: tool_categories::ORCHESTRATION,
        icon_id: "git-branch",
        simulator_app: AppChannels,
        app_subtool: SubTodo,
        chat_block: CbOrgTask,
        hidden: true,
        label_running: "tools.taskCreateRunning",
        label_done: "tools.taskCreateDone",
        label_failed: "tools.taskCreateFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::TASK_UPDATE,
        description: "Apply one authorized Task operation.",
        description_detail: "Applies one tagged graph-admin or Owner-lifecycle operation; mixed authority fields and terminal rewrites are rejected.",
        category: tool_categories::ORCHESTRATION,
        icon_id: "clipboard-pen",
        simulator_app: AppChannels,
        app_subtool: SubTodo,
        chat_block: CbOrgTask,
        hidden: true,
        label_running: "tools.taskUpdateRunning",
        label_done: "tools.taskUpdateDone",
        label_failed: "tools.taskUpdateFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::TASK_LIST,
        description: "List tasks on the Agent Org task board.",
        description_detail: "Lists shared task-board items for the current Agent Org run, optionally filtered by owner or status.",
        category: tool_categories::ORCHESTRATION,
        icon_id: "list-checks",
        simulator_app: AppChannels,
        app_subtool: SubTodo,
        chat_block: CbOrgTask,
        hidden: true,
        label_running: "tools.taskListRunning",
        label_done: "tools.taskListDone",
        label_failed: "tools.taskListFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::TASK_GET,
        description: "Fetch one Agent Org task.",
        description_detail: "Fetches one shared Agent Org task-board item by id with the full task payload.",
        category: tool_categories::ORCHESTRATION,
        icon_id: "clipboard-list",
        simulator_app: AppChannels,
        app_subtool: SubTodo,
        chat_block: CbOrgTask,
        hidden: true,
        label_running: "tools.taskGetRunning",
        label_done: "tools.taskGetDone",
        label_failed: "tools.taskGetFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::ORG_RUN_COMPLETE,
        description: "Request safe completion of an Agent Org run.",
        description_detail: "Records a coordinator completion request at the current work revision. It does not bypass task, delivery, approval, intervention, or turn-finality checks.",
        category: tool_categories::ORCHESTRATION,
        icon_id: "circle-check-big",
        simulator_app: AppChannels,
        app_subtool: SubTodo,
        chat_block: CbOrgTask,
        hidden: true,
        label_running: "tools.taskUpdateRunning",
        label_done: "tools.taskUpdateDone",
        label_failed: "tools.taskUpdateFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::ORG_INBOX_REPAIR,
        description: "Repair an undeliverable Agent Org Inbox row.",
        description_detail: "Coordinator-only. Inspects, cancels, or supersedes an Inbox delivery while preserving the original row as audit evidence.",
        category: tool_categories::ORCHESTRATION,
        icon_id: "mail-warning",
        simulator_app: AppChannels,
        app_subtool: SubTodo,
        chat_block: CbOrgTask,
        hidden: true,
        label_running: "tools.taskUpdateRunning",
        label_done: "tools.taskUpdateDone",
        label_failed: "tools.taskUpdateFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
];
