import { readFileSync } from "node:fs";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";

import { rpc } from "../../router";
import { ToolActionSchema, ToolInfoSchema } from "../tools";

const { invokeMock } = vi.hoisted(() => ({ invokeMock: vi.fn() }));
vi.mock("@tauri-apps/api/core", () => ({ invoke: invokeMock }));

// Generated by Rust's rust_tool_registry_matches_shared_frontend_contract. Keep the full
// payload comparison: parsing must preserve fields used by registry consumers.
const fixture = JSON.parse(
  readFileSync(
    path.resolve(process.cwd(), "src/test/fixtures/tool-registry.rust.json"),
    "utf8"
  )
) as {
  tools: Array<Record<string, unknown>>;
  cli_aliases: Record<string, unknown>;
};

afterEach(() => {
  invokeMock.mockReset();
  vi.unstubAllEnvs();
});

describe.each(["development", "production"])(
  "Rust tool registry RPC decoding in %s",
  (mode) => {
    it("preserves the complete registry, including tool and action display behavior", async () => {
      vi.stubEnv("NODE_ENV", mode);
      invokeMock.mockResolvedValue(fixture);

      await expect(rpc.tools.initToolRegistry()).resolves.toEqual(fixture);
      expect(invokeMock).toHaveBeenCalledWith("init_tool_registry", {});
    });

    it.each([
      ["listAllTools", "list_all_tools"],
      ["listAgentTools", "agent_list_tools"],
    ] as const)(
      "preserves each field returned by %s",
      async (method, command) => {
        vi.stubEnv("NODE_ENV", mode);
        invokeMock.mockResolvedValue(fixture.tools);

        await expect(rpc.tools[method]()).resolves.toEqual(fixture.tools);
        expect(invokeMock).toHaveBeenCalledWith(command, {});
      }
    );

    it("preserves prompt tool metadata in the effective session response", async () => {
      vi.stubEnv("NODE_ENV", mode);
      const response = {
        sessionId: "fixture-session",
        agentExecMode: "rust_agent",
        registeredToolNames: ["read_file"],
        promptToolNames: ["read_file"],
        deferredToolNames: [],
        promptTools: fixture.tools,
      };
      invokeMock.mockResolvedValue(response);

      await expect(
        rpc.tools.listEffectiveToolsForSession({
          request: { sessionId: response.sessionId },
        })
      ).resolves.toEqual(response);
    });
  }
);

describe("tool display behavior wire contract", () => {
  it("decodes every production tool without dropping metadata", () => {
    expect(fixture.tools.map((tool) => ToolInfoSchema.parse(tool))).toEqual(
      fixture.tools
    );
  });
  it.each(["instant", "stream", "wait_for_result"])(
    "retains Rust's %s value at both metadata levels",
    (displayBehavior) => {
      expect(
        ToolInfoSchema.parse({ ...fixture.tools[0], displayBehavior })
          .displayBehavior
      ).toBe(displayBehavior);
      expect(
        ToolActionSchema.parse({ name: "action", summary: "", displayBehavior })
          .displayBehavior
      ).toBe(displayBehavior);
    }
  );

  it("accepts omitted overrides but rejects values outside the Rust enum", () => {
    expect(ToolActionSchema.parse({ name: "action", summary: "" })).toEqual({
      name: "action",
      summary: "",
    });
    expect(
      ToolInfoSchema.safeParse({ ...fixture.tools[0], displayBehavior: "live" })
        .success
    ).toBe(false);
    expect(
      ToolActionSchema.safeParse({
        name: "action",
        summary: "",
        displayBehavior: "live",
      }).success
    ).toBe(false);
  });
});
