//! Typed Agent Org message payloads and their validation.
//!
//! `AgentMessage` is a discriminated union exchanged between sibling agents
//! inside an `AgentOrgRun`; the sibling `record` module persists it. See the
//! module-level docs on [`super`] for the audience/lifecycle distinction from
//! the user-facing `inbox` crate.

use serde::{Deserialize, Serialize};

use crate::coordination::agent_org_payload_limits as limits;
use crate::session::AgentExecMode;

pub fn is_supported_agent_org_remote_mode(mode: AgentExecMode) -> bool {
    matches!(
        mode,
        AgentExecMode::Build | AgentExecMode::Ask | AgentExecMode::Plan
    )
}

/// Wrapper around a UUID-ish string that correlates a request to a response.
///
/// Always client-generated by the sender (the LLM, in practice — it picks
/// the id and echoes it on the response). Required for every RPC-style
/// variant (`*Request`, `*Response`); ignored for `Plain` and one-shot
/// notifications.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RequestId(pub String);

impl RequestId {
    /// Generate a fresh UUID-backed id. Used by tests today and by the
    /// response path (auto-correlation when a worker replies via a
    /// non-LLM source, e.g. an internal cancellation timeout).
    pub fn new() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for RequestId {
    fn default() -> Self {
        Self::new()
    }
}

/// Typed message payload exchanged between agents inside an `AgentOrgRun`.
///
/// Each variant has its own validation rules — see [`AgentMessage::validate`].
///
/// ## Why so few variants
/// We deliberately keep this enum minimal. orgii already has a permission
/// system (`interaction::permission`) and a mode-switch system
/// (`interaction::mode_switch`) that talk to the **user**, not other agents.
/// A second agent-bus shadow of those would be a parallel implementation
/// with no real receiver. Only variants with a concrete caller AND a
/// concrete recipient outcome survive:
///
///   * `Plain` — free-form text (the common case).
///   * `Shutdown{Request,Response}` — graceful coordinator-driven worker
///     termination.
///   * `PlanApproval{Request,Response}` — a planning task assignment starts
///     the member in Plan mode automatically. `create_plan` persists a
///     task-bound approval; coordinator rejection is delivered as a
///     `PlanApprovalResponse` so the member can revise. Approval itself
///     completes the planning task and unlocks dependent work, without a
///     fake Build turn for the Planner.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind")]
pub enum AgentMessage {
    /// Free-form text. `summary` is a short label used in tool listings;
    /// `text` is the body delivered into the recipient's transcript.
    Plain { summary: String, text: String },

    /// Coordinator → worker: please wind down and exit. Response is
    /// `ShutdownResponse`.
    ShutdownRequest {
        request_id: RequestId,
        reason: Option<String>,
    },
    ShutdownResponse {
        request_id: RequestId,
        accepted: bool,
        note: Option<String>,
    },

    /// Member → coordinator: "I drafted a plan, please approve."
    /// Sent by `create_plan` when the calling session participates in
    /// an org and is not the coordinator. The coordinator's LLM is
    /// expected to reply with `PlanApprovalResponse` echoing the same
    /// `request_id`.
    ///
    /// `plan_path` is the absolute path to the plan markdown file on
    /// disk so the coordinator can read it directly with `read_file`
    /// if the inline `plan_content` excerpt is not enough. `plan_title`
    /// is the human-friendly label used by `create_plan`.
    PlanApprovalRequest {
        request_id: RequestId,
        approval_id: String,
        plan_revision_id: String,
        source_task_id: String,
        plan_title: String,
        plan_path: String,
        plan_content: String,
    },

    /// Coordinator → member: "I reviewed your plan."
    ///
    /// New rows are used for rejection/revision: `accepted = false` keeps
    /// the member in Plan mode. Deserializing accepted responses remains
    /// supported for historical inbox rows created before task-bound
    /// approvals; their `next_mode` defaults to Build.
    PlanApprovalResponse {
        request_id: RequestId,
        accepted: bool,
        feedback: Option<String>,
        next_mode: Option<AgentExecMode>,
    },

    /// Durable Coordinator-facing fact that an immutable Plan revision was
    /// decided. The Planner receives the separate response row when changes
    /// are requested; this projection exists so a user or automatic decision
    /// cannot bypass Coordinator convergence.
    PlanDecisionCommitted {
        approval_id: String,
        plan_revision_id: String,
        source_task_id: String,
        outcome: PlanDecisionOutcome,
        decided_by: PlanDecisionActor,
        feedback: Option<String>,
        task_output_digest: Option<String>,
        remaining_open_task_count: usize,
    },

    /// System → coordinator: "member `<member_id>` (a.k.a. `<member_name>`)
    /// has been terminated."
    ///
    /// Emitted by the coordinator-side inbox-drain side-effect path
    /// when it observes a `ShutdownResponse{accepted=true}` from a
    /// member (after issuing `cancel_session` on the member's runtime).
    /// Without it the coordinator's LLM has no signal that the worker
    /// is gone and may keep dispatching tasks into a dead inbox.
    ///
    /// Not LLM-callable: `org_send_message` rejects this kind, and the
    /// `sender_agent_id` of the inbox row MUST equal [`SYSTEM_SENDER_ID`]
    /// (`"_system"`) so a member cannot forge another member's termination
    /// notification. Both invariants are pinned by unit + E2E tests.
    ///
    /// [`SYSTEM_SENDER_ID`]: super::SYSTEM_SENDER_ID
    MemberTerminated {
        member_id: String,
        member_name: String,
        reason: MemberTerminationReason,
    },

    /// System → coordinator: "member `<agent_id>` is idle."
    ///
    /// Emitted at every member transition to idle so the coordinator's
    /// LLM has a positive signal that the worker finished its current
    /// turn / errored out / was interrupted, instead of having to poll
    /// session status out-of-band.
    ///
    /// Uses the same system-sender pattern as `MemberTerminated` so
    /// the worker session
    /// does not need a write handle into another session's inbox table.
    /// The coordinator-side hook in `inbox_drain` observes member-session
    /// finalize transitions and stamps the row with [`SYSTEM_SENDER_ID`].
    ///
    /// The fields cover everything orgii can faithfully populate: who,
    /// why, and the optional last-message summary the LLM uses to
    /// compose its next dispatch.
    ///
    /// Not LLM-callable: `org_send_message` rejects this kind for the
    /// same reasoning as `MemberTerminated` — allowing a member to forge
    /// peer-idle notifications would let it spoof another member's
    /// completion state and trick the coordinator into double-dispatch.
    ///
    /// [`SYSTEM_SENDER_ID`]: super::SYSTEM_SENDER_ID
    MemberIdle {
        member_id: String,
        member_name: String,
        reason: MemberIdleReason,
        /// Execution mode the member ended the turn in. This is
        /// coordinator-facing evidence for remote mode control: after an
        /// `exec_mode_set_request`, the next `member_idle` row should show
        /// the mode that actually ran.
        current_mode: Option<AgentExecMode>,
        /// Short XML-safe blurb extracted from the member's last
        /// outbound DM this turn. `None` is allowed — turn end without
        /// an outbound DM is a valid (and common) idle transition.
        summary: Option<String>,
        /// Free-form runtime error string when `reason == Failed`.
        /// Required iff `Failed`; rejected otherwise. Validated by
        /// [`AgentMessage::validate`].
        failure_reason: Option<String>,
        /// Build tasks that still remain `in_progress` even though this
        /// member has reached an idle turn boundary. Kept separate from
        /// `reason`: session availability and task finality are independent.
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        unfinished_task_ids: Vec<String>,
    },

    /// System → owner: "you have been assigned task `<task_id>`."
    ///
    /// Emitted whenever an authorized task mutation explicitly sets or
    /// changes a task's `owner` field.
    ///
    /// This row is enqueued by the `task_create`/`task_update` LLM
    /// tools and assignment recovery. It is *not* LLM-callable
    /// via `org_send_message` — fabricating an assignment would let
    /// any member redirect the coordinator's task graph. The producer
    /// stamps `sender_agent_id` with whoever caused the assignment (the
    /// assigning member's `agent_id`, or [`SYSTEM_SENDER_ID`] for
    /// scheduler redelivery of an existing explicit assignment).
    ///
    /// `subject` / `description` are denormalized snapshots of the
    /// assigned [`agent_org_tasks::Task`](super::super::agent_org_tasks::Task)
    /// row at the moment of assignment, so the recipient's LLM can
    /// render the assignment in the inbox-drain prompt without an extra
    /// store lookup. The authoritative copy lives in `agent_org_tasks`.
    /// `assigned_by` is the human-readable display name; the wire-level
    /// identity of the producer is `sender_agent_id` on the row.
    ///
    /// [`SYSTEM_SENDER_ID`]: super::SYSTEM_SENDER_ID
    TaskAssigned {
        task_id: String,
        subject: String,
        description: String,
        assigned_by: String,
        /// Task-scoped execution mode chosen by the coordinator. Historical
        /// rows without this field retain Build semantics.
        #[serde(default = "default_task_execution_mode")]
        execution_mode: crate::coordination::agent_org_tasks::TaskExecutionMode,
        /// Durable outputs of every completed blocker, copied into the
        /// assignment so the recipient never needs another session's chat.
        #[serde(default)]
        dependency_outputs: Vec<TaskDependencyOutput>,
    },

    /// Durable Coordinator-facing fact that a formal Task assignment was
    /// committed by another Writer or by a lifecycle transaction. This is a
    /// board observation, not executable work for the Coordinator; the owner
    /// receives the separate `TaskAssigned` row above.
    TaskAssignmentCommitted {
        task_id: String,
        owner_member_id: String,
        subject: String,
        assigned_by: String,
    },

    /// System → coordinator: an owner persisted a completed task and its
    /// durable output. Unlike `MemberIdle`, this is a task fact, not a session
    /// liveness hint, so the coordinator can immediately refresh the board.
    TaskCompleted {
        task_id: String,
        subject: String,
        completed_by_member_id: String,
        output_summary: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        plan_revision_id: Option<String>,
        remaining_open_task_count: usize,
    },

    /// System → coordinator: a Task reached a failed or cancelled terminal
    /// state. This is a board fact, not free-form narration, and therefore
    /// owns one exact formal trigger just like `TaskCompleted`.
    TaskTerminal {
        task_id: String,
        subject: String,
        terminal_status: TaskTerminalStatus,
        terminal_by_member_id: String,
        reason_code: String,
        reason_message: String,
        remaining_open_task_count: usize,
    },

    /// Historical coordinator → member execution-mode request.
    ///
    /// New Agent Org task assignments carry `execution_mode` directly and
    /// `org_send_message` no longer exposes this variant to the LLM. It stays
    /// deserializable so inbox rows created by older builds remain readable.
    /// The member's drain applies it before the next turn starts, and the next
    /// `MemberIdle` carries the mode the member actually ended the turn in (the LLM can read that to
    /// confirm the switch took).
    ///
    /// `reason` is an optional human blurb the recipient can echo into
    /// its system prompt the same turn (mirrors how
    /// `PlanApprovalResponse.feedback` is wired). Bounded length so a
    /// runaway prompt cannot blow up history.
    ExecModeSetRequest {
        request_id: RequestId,
        mode: AgentExecMode,
        reason: Option<String>,
    },
}

fn default_task_execution_mode() -> crate::coordination::agent_org_tasks::TaskExecutionMode {
    crate::coordination::agent_org_tasks::TaskExecutionMode::Build
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct TaskDependencyOutput {
    pub task_id: String,
    pub subject: String,
    pub summary: String,
    pub content: Option<String>,
    pub artifact_ids: Vec<String>,
    pub produced_by_member_id: String,
}

/// Why a member was terminated. Stable wire string so coordinator-side
/// LLM prompts can branch on it without re-parsing freeform text.
///
/// Today the only producer is the shutdown-handshake side-effect path, so
/// only the `Shutdown` variant is emitted. Other reasons (crash, cancel,
/// timeout) are reserved for follow-up phases.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemberTerminationReason {
    /// The member acknowledged a shutdown request (or volunteered one)
    /// via `ShutdownResponse{accepted=true}`, and the coordinator-side
    /// drain cancelled the session in response. This is the protocol
    /// happy path.
    Shutdown,
}

/// Why a member became idle.
///
/// `Available` — the member finished its turn cleanly and is ready for
/// the next dispatch. `Interrupted` — a user/coordinator cancel landed
/// mid-turn. `Failed` — the member hit a runtime error during the turn
/// and surfaces `failure_reason` for the coordinator's LLM.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemberIdleReason {
    Available,
    Interrupted,
    Failed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskTerminalStatus {
    Failed,
    Cancelled,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanDecisionOutcome {
    Approved,
    ChangesRequested,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanDecisionActor {
    User,
    Coordinator,
    Automatic,
}

impl AgentMessage {
    /// Stable discriminator string persisted alongside the JSON payload.
    /// Must round-trip with the serde tag; if the enum is renamed, update
    /// both sides simultaneously.
    pub fn kind_tag(&self) -> &'static str {
        match self {
            Self::Plain { .. } => "plain",
            Self::ShutdownRequest { .. } => "shutdown_request",
            Self::ShutdownResponse { .. } => "shutdown_response",
            Self::PlanApprovalRequest { .. } => "plan_approval_request",
            Self::PlanApprovalResponse { .. } => "plan_approval_response",
            Self::PlanDecisionCommitted { .. } => "plan_decision_committed",
            Self::MemberTerminated { .. } => "member_terminated",
            Self::MemberIdle { .. } => "member_idle",
            Self::TaskAssigned { .. } => "task_assigned",
            Self::TaskAssignmentCommitted { .. } => "task_assignment_committed",
            Self::TaskCompleted { .. } => "task_completed",
            Self::TaskTerminal { .. } => "task_terminal",
            Self::ExecModeSetRequest { .. } => "exec_mode_set_request",
        }
    }

    /// `RequestId` carried by RPC variants, if any.
    pub fn request_id(&self) -> Option<&RequestId> {
        match self {
            Self::ShutdownRequest { request_id, .. }
            | Self::ShutdownResponse { request_id, .. }
            | Self::PlanApprovalRequest { request_id, .. }
            | Self::PlanApprovalResponse { request_id, .. }
            | Self::ExecModeSetRequest { request_id, .. } => Some(request_id),
            Self::Plain { .. }
            | Self::PlanDecisionCommitted { .. }
            | Self::MemberTerminated { .. }
            | Self::MemberIdle { .. }
            | Self::TaskAssigned { .. }
            | Self::TaskAssignmentCommitted { .. }
            | Self::TaskCompleted { .. }
            | Self::TaskTerminal { .. } => None,
        }
    }

    /// Whether this variant carries an RPC-style structured payload (vs
    /// plain free-form text). Used by `org_send_message` to enforce the
    /// "broadcast must be plain only" invariant — structured RPCs need a
    /// 1:1 correlation between sender and recipient via `request_id`,
    /// which is incoherent with fan-out.
    ///
    /// `MemberTerminated` is structured (typed payload, system-emitted),
    /// even though it has no `request_id`: the broadcast guard rejects
    /// it because broadcasting a member-termination notice to every member
    /// is nonsensical, and `org_send_message` rejects it outright as
    /// non-LLM-callable.
    pub fn is_structured(&self) -> bool {
        match self {
            Self::Plain { .. } => false,
            Self::ShutdownRequest { .. }
            | Self::ShutdownResponse { .. }
            | Self::PlanApprovalRequest { .. }
            | Self::PlanApprovalResponse { .. }
            | Self::PlanDecisionCommitted { .. }
            | Self::MemberTerminated { .. }
            | Self::MemberIdle { .. }
            | Self::TaskAssigned { .. }
            | Self::TaskAssignmentCommitted { .. }
            | Self::TaskCompleted { .. }
            | Self::TaskTerminal { .. }
            | Self::ExecModeSetRequest { .. } => true,
        }
    }

    /// Validate variant invariants prior to persistence.
    ///
    /// Returns a stable error string suitable to surface back to the LLM
    /// via tool error reporting.
    pub fn validate(&self) -> Result<(), String> {
        if let Some(request_id) = self.request_id() {
            limits::validate_message_identifier("request_id", request_id.as_str())?;
        }
        match self {
            Self::Plain { summary, text } => {
                limits::validate_required_text(
                    "Plain.summary",
                    summary,
                    limits::PLAIN_SUMMARY_MAX_CHARS,
                    limits::PLAIN_SUMMARY_MAX_BYTES,
                )?;
                limits::validate_required_text(
                    "Plain.text",
                    text,
                    limits::PLAIN_TEXT_MAX_CHARS,
                    limits::PLAIN_TEXT_MAX_BYTES,
                )?;
            }
            Self::ShutdownRequest { reason, .. } => {
                limits::validate_optional_text(
                    "ShutdownRequest.reason",
                    reason.as_deref(),
                    limits::SHUTDOWN_NOTE_MAX_CHARS,
                    limits::SHUTDOWN_NOTE_MAX_BYTES,
                )?;
            }
            Self::ShutdownResponse { note, .. } => {
                limits::validate_optional_text(
                    "ShutdownResponse.note",
                    note.as_deref(),
                    limits::SHUTDOWN_NOTE_MAX_CHARS,
                    limits::SHUTDOWN_NOTE_MAX_BYTES,
                )?;
            }
            Self::PlanApprovalRequest {
                approval_id,
                plan_revision_id,
                source_task_id,
                plan_title,
                plan_path,
                plan_content,
                ..
            } => {
                limits::validate_required_text(
                    "PlanApprovalRequest.plan_title",
                    plan_title,
                    limits::PLAN_TITLE_MAX_CHARS,
                    limits::PLAN_TITLE_MAX_BYTES,
                )?;
                limits::validate_message_identifier(
                    "PlanApprovalRequest.approval_id",
                    approval_id,
                )?;
                limits::validate_message_identifier(
                    "PlanApprovalRequest.plan_revision_id",
                    plan_revision_id,
                )?;
                limits::validate_task_identifier(
                    "PlanApprovalRequest.source_task_id",
                    source_task_id,
                )?;
                limits::validate_required_text(
                    "PlanApprovalRequest.plan_path",
                    plan_path,
                    limits::PLAN_PATH_MAX_CHARS,
                    limits::PLAN_PATH_MAX_BYTES,
                )?;
                limits::validate_required_text(
                    "PlanApprovalRequest.plan_content",
                    plan_content,
                    limits::INLINE_PLAN_CONTENT_MAX_CHARS,
                    limits::INLINE_PLAN_CONTENT_MAX_BYTES,
                )?;
            }
            Self::PlanApprovalResponse {
                feedback,
                next_mode,
                ..
            } => {
                if let Some(mode) = next_mode {
                    if !is_supported_agent_org_remote_mode(*mode) {
                        return Err(
                            "PlanApprovalResponse.next_mode must be one of: build, ask, plan"
                                .into(),
                        );
                    }
                }
                limits::validate_optional_text(
                    "PlanApprovalResponse.feedback",
                    feedback.as_deref(),
                    limits::PLAN_FEEDBACK_MAX_CHARS,
                    limits::PLAN_FEEDBACK_MAX_BYTES,
                )?;
            }
            Self::MemberTerminated {
                member_id,
                member_name,
                ..
            } => {
                limits::validate_message_identifier("MemberTerminated.member_id", member_id)?;
                limits::validate_required_text(
                    "MemberTerminated.member_name",
                    member_name,
                    limits::MEMBER_DISPLAY_NAME_MAX_CHARS,
                    limits::MEMBER_DISPLAY_NAME_MAX_BYTES,
                )?;
            }
            Self::MemberIdle {
                member_id,
                member_name,
                reason,
                summary,
                failure_reason,
                unfinished_task_ids,
                ..
            } => {
                limits::validate_message_identifier("MemberIdle.member_id", member_id)?;
                limits::validate_required_text(
                    "MemberIdle.member_name",
                    member_name,
                    limits::MEMBER_DISPLAY_NAME_MAX_CHARS,
                    limits::MEMBER_DISPLAY_NAME_MAX_BYTES,
                )?;
                limits::validate_optional_text(
                    "MemberIdle.summary",
                    summary.as_deref(),
                    limits::MEMBER_SUMMARY_MAX_CHARS,
                    limits::MEMBER_SUMMARY_MAX_BYTES,
                )?;
                if unfinished_task_ids.len() > 32 {
                    return Err(
                        "MemberIdle.unfinished_task_ids must contain at most 32 task ids".into(),
                    );
                }
                limits::validate_task_identifier_list(
                    "MemberIdle.unfinished_task_ids",
                    unfinished_task_ids,
                )?;
                match reason {
                    MemberIdleReason::Failed => {
                        let fr = failure_reason.as_deref().unwrap_or("").trim();
                        limits::validate_required_text(
                            "MemberIdle.failure_reason",
                            fr,
                            limits::MEMBER_FAILURE_REASON_MAX_CHARS,
                            limits::MEMBER_FAILURE_REASON_MAX_BYTES,
                        )?;
                    }
                    MemberIdleReason::Available | MemberIdleReason::Interrupted => {
                        if failure_reason.is_some() {
                            return Err(
                                "MemberIdle.failure_reason is only valid when reason='failed'"
                                    .into(),
                            );
                        }
                    }
                }
            }
            Self::PlanDecisionCommitted {
                approval_id,
                plan_revision_id,
                source_task_id,
                outcome,
                feedback,
                task_output_digest,
                ..
            } => {
                limits::validate_message_identifier(
                    "PlanDecisionCommitted.approval_id",
                    approval_id,
                )?;
                limits::validate_message_identifier(
                    "PlanDecisionCommitted.plan_revision_id",
                    plan_revision_id,
                )?;
                limits::validate_task_identifier(
                    "PlanDecisionCommitted.source_task_id",
                    source_task_id,
                )?;
                limits::validate_optional_text(
                    "PlanDecisionCommitted.feedback",
                    feedback.as_deref(),
                    limits::PLAN_FEEDBACK_MAX_CHARS,
                    limits::PLAN_FEEDBACK_MAX_BYTES,
                )?;
                match outcome {
                    PlanDecisionOutcome::Approved if feedback.is_some() => {
                        return Err(
                            "PlanDecisionCommitted approved outcome cannot carry feedback".into(),
                        );
                    }
                    PlanDecisionOutcome::ChangesRequested
                        if feedback
                            .as_deref()
                            .is_none_or(|feedback| feedback.trim().is_empty()) =>
                    {
                        return Err(
                            "PlanDecisionCommitted changes_requested requires feedback".into()
                        );
                    }
                    _ => {}
                }
                match (outcome, task_output_digest.as_deref()) {
                    (PlanDecisionOutcome::Approved, Some(digest))
                        if digest.len() == 64
                            && digest.bytes().all(|byte| byte.is_ascii_hexdigit()) => {}
                    (PlanDecisionOutcome::Approved, _) => {
                        return Err(
                            "PlanDecisionCommitted approved outcome requires a SHA-256 TaskOutput digest"
                                .into(),
                        );
                    }
                    (PlanDecisionOutcome::ChangesRequested, None) => {}
                    (PlanDecisionOutcome::ChangesRequested, Some(_)) => {
                        return Err(
                            "PlanDecisionCommitted changes_requested cannot carry a TaskOutput digest"
                                .into(),
                        );
                    }
                }
            }
            Self::TaskAssigned {
                task_id,
                subject,
                assigned_by,
                description,
                dependency_outputs,
                ..
            } => {
                limits::validate_task_identifier("TaskAssigned.task_id", task_id)?;
                if dependency_outputs.len() > limits::TASK_DEPENDENCY_OUTPUT_MAX_COUNT {
                    return Err(format!(
                        "TaskAssigned.dependency_outputs must contain at most {} entries",
                        limits::TASK_DEPENDENCY_OUTPUT_MAX_COUNT
                    ));
                }
                limits::validate_required_text(
                    "TaskAssigned.subject",
                    subject,
                    limits::TASK_SUBJECT_MAX_CHARS,
                    limits::TASK_SUBJECT_MAX_BYTES,
                )?;
                limits::validate_required_text(
                    "TaskAssigned.assigned_by",
                    assigned_by,
                    limits::ASSIGNED_BY_MAX_CHARS,
                    limits::ASSIGNED_BY_MAX_BYTES,
                )?;
                limits::validate_text_len(
                    "TaskAssigned.description",
                    description,
                    limits::TASK_DESCRIPTION_MAX_CHARS,
                    limits::TASK_DESCRIPTION_MAX_BYTES,
                )?;
                for output in dependency_outputs {
                    if output.task_id.trim().is_empty()
                        || output.subject.trim().is_empty()
                        || output.summary.trim().is_empty()
                        || output.produced_by_member_id.trim().is_empty()
                    {
                        return Err(
                            "TaskAssigned.dependency_outputs entries require task_id, subject, summary, and produced_by_member_id"
                                .into(),
                        );
                    }
                    limits::validate_task_identifier(
                        "TaskAssigned dependency task_id",
                        &output.task_id,
                    )?;
                    limits::validate_message_identifier(
                        "TaskAssigned dependency produced_by_member_id",
                        &output.produced_by_member_id,
                    )?;
                    limits::validate_required_text(
                        "TaskAssigned dependency subject",
                        &output.subject,
                        limits::TASK_SUBJECT_MAX_CHARS,
                        limits::TASK_SUBJECT_MAX_BYTES,
                    )?;
                    limits::validate_required_text(
                        "TaskAssigned dependency summary",
                        &output.summary,
                        limits::TASK_OUTPUT_SUMMARY_MAX_CHARS,
                        limits::TASK_OUTPUT_SUMMARY_MAX_BYTES,
                    )?;
                    limits::validate_optional_text(
                        "TaskAssigned dependency content",
                        output.content.as_deref(),
                        limits::TASK_OUTPUT_CONTENT_MAX_CHARS,
                        limits::TASK_OUTPUT_CONTENT_MAX_BYTES,
                    )?;
                    limits::validate_task_artifact_ids(
                        "TaskAssigned dependency artifact_ids",
                        &output.artifact_ids,
                    )?;
                }
                let total_inline_chars: usize = dependency_outputs
                    .iter()
                    .filter_map(|output| output.content.as_ref())
                    .map(|content| content.chars().count())
                    .sum();
                if total_inline_chars > limits::TASK_DEPENDENCY_TOTAL_CONTENT_MAX_CHARS {
                    return Err(format!(
                        "TaskAssigned.dependency_outputs total inline content must be <= {} chars; use artifacts for larger handoffs",
                        limits::TASK_DEPENDENCY_TOTAL_CONTENT_MAX_CHARS
                    ));
                }
                let total_inline_bytes: usize = dependency_outputs
                    .iter()
                    .filter_map(|output| output.content.as_ref())
                    .map(String::len)
                    .sum();
                if total_inline_bytes > limits::TASK_DEPENDENCY_TOTAL_CONTENT_MAX_BYTES {
                    return Err(format!(
                        "TaskAssigned.dependency_outputs total inline content must be <= {} bytes; use artifacts for larger handoffs",
                        limits::TASK_DEPENDENCY_TOTAL_CONTENT_MAX_BYTES
                    ));
                }
            }
            Self::TaskAssignmentCommitted {
                task_id,
                owner_member_id,
                subject,
                assigned_by,
            } => {
                limits::validate_task_identifier("TaskAssignmentCommitted.task_id", task_id)?;
                limits::validate_message_identifier(
                    "TaskAssignmentCommitted.owner_member_id",
                    owner_member_id,
                )?;
                limits::validate_required_text(
                    "TaskAssignmentCommitted.subject",
                    subject,
                    limits::TASK_SUBJECT_MAX_CHARS,
                    limits::TASK_SUBJECT_MAX_BYTES,
                )?;
                limits::validate_required_text(
                    "TaskAssignmentCommitted.assigned_by",
                    assigned_by,
                    limits::ASSIGNED_BY_MAX_CHARS,
                    limits::ASSIGNED_BY_MAX_BYTES,
                )?;
            }
            Self::TaskCompleted {
                task_id,
                subject,
                completed_by_member_id,
                output_summary,
                plan_revision_id,
                ..
            } => {
                limits::validate_task_identifier("TaskCompleted.task_id", task_id)?;
                limits::validate_required_text(
                    "TaskCompleted.subject",
                    subject,
                    limits::TASK_SUBJECT_MAX_CHARS,
                    limits::TASK_SUBJECT_MAX_BYTES,
                )?;
                limits::validate_message_identifier(
                    "TaskCompleted.completed_by_member_id",
                    completed_by_member_id,
                )?;
                limits::validate_optional_text(
                    "TaskCompleted.output_summary",
                    output_summary.as_deref(),
                    limits::TASK_OUTPUT_SUMMARY_MAX_CHARS,
                    limits::TASK_OUTPUT_SUMMARY_MAX_BYTES,
                )?;
                if let Some(plan_revision_id) = plan_revision_id.as_deref() {
                    limits::validate_message_identifier(
                        "TaskCompleted.plan_revision_id",
                        plan_revision_id,
                    )?;
                }
            }
            Self::TaskTerminal {
                task_id,
                subject,
                terminal_by_member_id,
                reason_code,
                reason_message,
                ..
            } => {
                limits::validate_task_identifier("TaskTerminal.task_id", task_id)?;
                limits::validate_required_text(
                    "TaskTerminal.subject",
                    subject,
                    limits::TASK_SUBJECT_MAX_CHARS,
                    limits::TASK_SUBJECT_MAX_BYTES,
                )?;
                limits::validate_message_identifier(
                    "TaskTerminal.terminal_by_member_id",
                    terminal_by_member_id,
                )?;
                limits::validate_message_identifier("TaskTerminal.reason_code", reason_code)?;
                limits::validate_required_text(
                    "TaskTerminal.reason_message",
                    reason_message,
                    limits::MEMBER_FAILURE_REASON_MAX_CHARS,
                    limits::MEMBER_FAILURE_REASON_MAX_BYTES,
                )?;
            }
            Self::ExecModeSetRequest { mode, reason, .. } => {
                if !is_supported_agent_org_remote_mode(*mode) {
                    return Err("ExecModeSetRequest.mode must be one of: build, ask, plan".into());
                }
                limits::validate_optional_text(
                    "ExecModeSetRequest.reason",
                    reason.as_deref(),
                    limits::EXEC_MODE_REASON_MAX_CHARS,
                    limits::EXEC_MODE_REASON_MAX_BYTES,
                )?;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
#[path = "message_tests.rs"]
mod tests;
